export const REGISTER_USER = 'REGISTERING_USER';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const LOGINING_USER = 'LOGINING_USER';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
